image: gorzechowski/gcc

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  stage: build
  before_script:
    - chmod +x vendor/bin/premake/premake5linux
    - apt-get update
    - apt-get install -y libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev 
    - vendor/bin/premake/premake5linux gmake2
  script:
    - make
  artifacts:
    paths:
      - bin/Debug-linux-x86_64/Sandbox/Sandbox
      - bin/Debug-linux-x86_64/InternalEngine/libInternalEngine.a